services:
  hub:
    build: ./hub
    networks:
      - webnet
    ports:
      - "8000:5000"
    environment:
      REDIS_URL: redis://redis:6379/0
      FLASK_ENV: development
      FLASK_APP: app:app
    env_file:
      - .env

  site1:
    build: ./site1
    networks:
      - webnet
    ports:
      - "8001:5001"
    env_file:
      - .env
      
  site2:
    build: ./site2
    networks:
      - webnet
    ports:
      - "8002:5002"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:latest
    networks:
      - webnet

networks:
  webnet:
    driver: bridge